# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f1377d99aca13653398cbd95dca28363386db3632a4a84a64133dfff9f57fd4f85b0c6572a482e800bf140dcc2c924b6f8cfb5852d1de96d38ccf7ea3f81d58

test:
  secret_key_base: b8c8df166d547b1c5188eb79b54aad410af40ce41631d36f2113199c97c56640dce55a5cec5ae14ee2d17af39176e6223e689039b5f2f1e9d028f2580b671e69

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
